# Generated by Django 2.1.14 on 2020-01-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200113_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblaliquotbdm3',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={},
        ),
    ]
