# Generated by Django 2.1.14 on 2020-01-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200115_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblaliquotbdm3',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={'managed': False},
        ),
    ]
