# Generated by Django 2.1.14 on 2020-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_aliquot_trans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqid', models.CharField(blank=True, db_column='AqID', max_length=50, null=True)),
                ('boxid', models.CharField(blank=True, db_column='BoxID', max_length=50, null=True)),
                ('updated', models.IntegerField(db_column='Updated', default=0)),
                ('date_updated', models.DateTimeField(blank=True, db_column='Date_Updated', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aliquot_trans',
            name='boxid',
            field=models.CharField(blank=True, db_column='BoxID', max_length=50, null=True),
        ),
    ]
