# Generated by Django 2.1.14 on 2020-01-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_create_aliquot_trans_create_box_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_aliquot_trans',
            name='date_created',
            field=models.DateTimeField(blank=True, db_column='Date_Created', null=True),
        ),
        migrations.AlterField(
            model_name='create_box_trans',
            name='date_created',
            field=models.DateTimeField(blank=True, db_column='Date_Created', null=True),
        ),
    ]
