# Generated by Django 2.1.14 on 2020-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_aliquotlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
                ('datetime_login', models.DateTimeField(blank=True, db_column='Datetime_logged_in', null=True)),
                ('logged_in', models.IntegerField(db_column='logged_in', default=0)),
                ('datetime_logout', models.DateTimeField(blank=True, db_column='Datetime_logged_out', null=True)),
                ('logged_out', models.IntegerField(db_column='logged_out', default=0)),
            ],
        ),
    ]
