# Generated by Django 2.1.14 on 2020-02-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20200219_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tupinventorya',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tupinventoryb',
            options={},
        ),
    ]
