# Generated by Django 2.1.14 on 2020-02-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20200227_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tupinventorya',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tupinventoryb',
            options={},
        ),
    ]
