# Generated by Django 2.1.14 on 2020-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_tupsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUpSearchTest',
            fields=[
                ('lotid', models.CharField(blank=True, db_column='LotID', max_length=50, null=True)),
                ('trialkey', models.CharField(blank=True, db_column='TrialKey', max_length=50, null=True)),
                ('studyid', models.CharField(blank=True, db_column='StudyID', max_length=50, null=True)),
                ('studydesc', models.CharField(blank=True, db_column='StudyDesc', max_length=200, null=True)),
                ('aqid', models.CharField(db_column='AqID', max_length=50, primary_key=True, serialize=False)),
                ('originalid', models.CharField(blank=True, db_column='OriginalID', max_length=255, null=True)),
                ('grid', models.CharField(blank=True, db_column='Grid', max_length=50, null=True)),
                ('labelinfo', models.TextField(blank=True, db_column='LabelInfo', null=True)),
                ('volume', models.DecimalField(blank=True, db_column='Volume', decimal_places=3, max_digits=18, null=True)),
                ('insertdate', models.DateTimeField(blank=True, db_column='InsertDate', null=True)),
                ('invnum', models.CharField(blank=True, db_column='InvNum', max_length=50, null=True)),
                ('invcomment', models.TextField(blank=True, db_column='InvComment', null=True)),
                ('checkout', models.IntegerField(db_column='CheckOut')),
                ('date_changed', models.DateTimeField(blank=True, db_column='Date_Changed', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=50, null=True)),
                ('demogroup', models.CharField(blank=True, db_column='DemoGroup', max_length=50, null=True)),
                ('riskcategory', models.CharField(blank=True, db_column='RiskCategory', max_length=50, null=True)),
                ('riskgroupdesc', models.CharField(blank=True, db_column='RiskGroupDesc', max_length=50, null=True)),
                ('bloodtype', models.CharField(blank=True, db_column='BloodType', max_length=50, null=True)),
                ('hiv1', models.CharField(blank=True, db_column='HIV1', max_length=50, null=True)),
                ('hiv2', models.CharField(blank=True, db_column='HIV2', max_length=50, null=True)),
                ('hivo', models.CharField(blank=True, db_column='HIVO', max_length=50, null=True)),
                ('hbs', models.CharField(blank=True, db_column='HBs', max_length=50, null=True)),
                ('hbc', models.CharField(blank=True, db_column='HBc', max_length=50, null=True)),
                ('hav', models.CharField(blank=True, db_column='HAV', max_length=50, null=True)),
                ('hcv', models.CharField(blank=True, db_column='HCV', max_length=50, null=True)),
                ('mmrv', models.CharField(blank=True, db_column='MMRV', max_length=50, null=True)),
                ('influenza', models.CharField(blank=True, db_column='Influenza', max_length=50, null=True)),
                ('sars_cov2', models.CharField(blank=True, db_column='SARS_COV2', max_length=50, null=True)),
                ('other', models.CharField(blank=True, db_column='Other', max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=50, null=True)),
                ('panelname', models.CharField(blank=True, db_column='PanelName', max_length=50, null=True)),
                ('paneldesc', models.CharField(blank=True, db_column='PanelDesc', max_length=50, null=True)),
                ('membernum', models.CharField(blank=True, db_column='MemberNum', max_length=50, null=True)),
                ('samtypedesc', models.CharField(blank=True, db_column='SamTypeDesc', max_length=50, null=True)),
                ('samprepdesc', models.CharField(blank=True, db_column='SamPrepDesc', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('dup', models.CharField(blank=True, db_column='Dup', max_length=50, null=True)),
                ('isconfirmed', models.CharField(blank=True, db_column='IsConfirmed', max_length=50, null=True)),
            ],
            options={
                'db_table': 't_up_search_test',
                'managed': False,
            },
        ),
    ]
