# Generated by Django 2.1 on 2020-08-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_tupsearchtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFreezeThawTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqid', models.CharField(blank=True, db_column='AqID', max_length=50, null=True)),
                ('freeze_thaw', models.IntegerField(blank=True, db_column='Freeze_Thaw', null=True)),
                ('datetime_freeze', models.DateTimeField(blank=True, db_column='DateTime_Freeze', null=True)),
                ('datetime_thaw', models.DateTimeField(blank=True, db_column='DateTime_Thaw', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
            ],
            options={
                'db_table': 'search_freeze_thaw_trans',
                'managed': False,
            },
        ),
    ]
