# Generated by Django 2.1 on 2020-08-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_searchfreezethawtrans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchfreezethawtrans',
            options={},
        ),
    ]
