# Generated by Django 2.1 on 2020-08-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_auto_20200812_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchFreezeThawTrans',
        ),
    ]
