# Generated by Django 2.1 on 2020-08-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_searchfreezethawtrans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchfreezethawtrans',
            options={},
        ),
    ]
