# Generated by Django 2.1 on 2020-10-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_searchshippingtrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRefSite',
            fields=[
                ('siteid', models.IntegerField(blank=True, db_column='SiteID', null=True)),
                ('sitestate', models.CharField(db_column='SiteState', max_length=50)),
                ('sitecountry', models.CharField(db_column='SiteCountry', max_length=50)),
                ('sitename', models.CharField(db_column='SiteName', max_length=255)),
                ('siteabbr', models.CharField(db_column='SiteAbbr', max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_ref_Site',
                'managed': False,
            },
        ),
    ]
