# Generated by Django 2.1 on 2020-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_trefsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCreateLocationTrans',
            fields=[
                ('create_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=50, null=True)),
                ('locatino_abbr', models.CharField(blank=True, db_column='Locatino_abbr', max_length=50, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date_created', null=True)),
            ],
            options={
                'db_table': 'search_create_location_trans',
                'managed': False,
            },
        ),
    ]
