# Generated by Django 2.1 on 2020-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_searchcreatelocationtrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUpCoa',
            fields=[
                ('year', models.CharField(blank=True, db_column='Year', max_length=5, null=True)),
                ('lotid', models.CharField(blank=True, db_column='LotID', max_length=20, primary_key=True, serialize=False)),
                ('field_field', models.CharField(blank=True, db_column='#', max_length=10, null=True)),
                ('originalid', models.CharField(blank=True, db_column='OriginalID', max_length=255, null=True)),
                ('cofa', models.TextField(blank=True, db_column='CofA', null=True)),
                ('pdf_contents', models.TextField(blank=True, db_column='PDF_Contents', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 't_up_CoA',
                'managed': False,
            },
        ),
    ]
