# Generated by Django 2.1.14 on 2020-01-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tupinventorya',
            name='invnum',
            field=models.IntegerField(blank=True, db_column='InvNum', null=True),
        ),
        migrations.AlterField(
            model_name='tupinventoryb',
            name='invcomments',
            field=models.TextField(blank=True, db_column='InvComments', null=True),
        ),
        migrations.AlterField(
            model_name='tupinventoryb',
            name='invnum',
            field=models.IntegerField(blank=True, db_column='InvNum', null=True),
        ),
    ]
