# Generated by Django 2.1.14 on 2020-01-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200115_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={},
        ),
    ]
