# Generated by Django 2.1.14 on 2020-01-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200116_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='tblboxinfo',
            name='boxid',
            field=models.OneToOneField(db_column='BoxID', max_length=255, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search.TUpInventoryb'),
        ),
        migrations.AlterField(
            model_name='tblboxinfo',
            name='boxtype',
            field=models.CharField(blank=True, db_column='BoxType', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblboxinfo',
            name='contents',
            field=models.CharField(blank=True, db_column='Contents', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblboxinfo',
            name='insertdate',
            field=models.DateTimeField(blank=True, db_column='InsertDate', null=True),
        ),
        migrations.AlterField(
            model_name='tblboxinfo',
            name='invstatus',
            field=models.CharField(blank=True, db_column='InvStatus', max_length=255, null=True),
        ),
    ]
