# Generated by Django 2.1.14 on 2020-01-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200116_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={},
        ),
        migrations.AddField(
            model_name='tupinventorya',
            name='checked_out',
            field=models.IntegerField(db_column='CheckOut', default=0),
        ),
        migrations.AddField(
            model_name='tupinventorya',
            name='datechanged',
            field=models.DateTimeField(auto_now=True, db_column='Date_Changed', null=True),
        ),
        migrations.AddField(
            model_name='tupinventorya',
            name='user',
            field=models.CharField(blank=True, db_column='User', max_length=50, null=True),
        ),
    ]
