# Generated by Django 2.1.14 on 2020-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200123_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliquot_Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqid', models.CharField(blank=True, db_column='AqID', max_length=50, null=True)),
                ('updated', models.IntegerField(db_column='Updated', default=0)),
                ('date_updated', models.DateTimeField(blank=True, db_column='Date_Updated', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
            ],
        ),
    ]
