# Generated by Django 2.1.14 on 2020-01-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_update_trans_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Aliquot_Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqid', models.CharField(blank=True, db_column='AqID', max_length=50, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date_Updated', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Box_Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxid', models.CharField(blank=True, db_column='AqID', max_length=50, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date_Updated', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
            ],
        ),
    ]
