# Generated by Django 2.1.14 on 2020-01-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20200124_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotList',
            fields=[
                ('aqid', models.CharField(db_column='AqID', max_length=50, primary_key=True, serialize=False)),
                ('originalid', models.CharField(blank=True, db_column='OriginalID', max_length=255, null=True)),
                ('grid', models.CharField(db_column='Grid', max_length=50)),
                ('labelinfo', models.TextField(db_column='LabelInfo')),
                ('volume', models.DecimalField(blank=True, db_column='Volume', decimal_places=3, max_digits=8, null=True)),
                ('insertdate', models.DateTimeField(db_column='InsertDate')),
                ('invnum', models.IntegerField(db_column='InvNum')),
                ('invcomment', models.TextField(blank=True, db_column='InvComment', null=True)),
                ('boxid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.TListInventoryb')),
            ],
            options={
                'db_table': 't_list_InventoryA',
            },
        ),
    ]
