# Generated by Django 2.1.14 on 2020-02-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_loginlogout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tupinventorya',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tupinventoryb',
            options={'managed': False},
        ),
    ]
