# Generated by Django 2.1.14 on 2020-02-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20200219_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblboxinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tupinventorya',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tupinventoryb',
            options={'managed': False},
        ),
    ]
