# Generated by Django 2.1 on 2020-08-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_delete_searchfreezethawtrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFreezeThawTrans',
            fields=[
                ('transaction_num', models.IntegerField(blank=True, db_column='Transaction_Num', primary_key=True, serialize=False)),
                ('freeze_thaw', models.IntegerField(blank=True, db_column='Freeze_Thaw', null=True)),
                ('datetime_freeze', models.DateTimeField(blank=True, db_column='DateTime_Freeze', null=True)),
                ('datetime_thaw', models.DateTimeField(blank=True, db_column='DateTime_Thaw', null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=10, null=True)),
            ],
            options={
                'db_table': 'search_freeze_thaw_trans',
                'managed': False,
            },
        ),
    ]
