# Generated by Django 2.1 on 2020-08-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_auto_20200814_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchfreezethawtrans',
            options={'managed': False},
        ),
    ]
