# Generated by Django 2.1 on 2020-09-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_searchreturntrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchShippingTrans',
            fields=[
                ('shipping_id', models.CharField(db_column='shipping_id', max_length=50, primary_key=True, serialize=False)),
                ('trans_id', models.IntegerField(db_column='trans_id')),
                ('aqid_out', models.CharField(blank=True, db_column='aqid_out', max_length=50, null=True)),
                ('boxid_out', models.CharField(blank=True, db_column='boxid_out', max_length=50, null=True)),
                ('ship_location', models.CharField(blank=True, db_column='ship_location', max_length=50, null=True)),
                ('date_shipped', models.DateTimeField(blank=True, db_column='date_shipped', null=True)),
                ('date_returned', models.DateTimeField(blank=True, db_column='date_returned', null=True)),
                ('boxid_in', models.CharField(blank=True, db_column='boxid_in', max_length=50, null=True)),
                ('user', models.CharField(blank=True, db_column='user', max_length=50, null=True)),
                ('condition', models.CharField(blank=True, db_column='condition', max_length=50, null=True)),
            ],
            options={
                'db_table': 'search_shipping_trans',
                'managed': False,
            },
        ),
    ]
