# Generated by Django 2.1.15 on 2021-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvpsyndromic', '0002_auto_20210126_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tstg1brpcr',
            name='id',
        ),
        migrations.AlterField(
            model_name='tstg1brpcr',
            name='sample',
            field=models.CharField(blank=True, db_column='Sample', default=0, max_length=25, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
