# Generated by Django 2.1.15 on 2021-01-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvpsyndromic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tstg1ecrf',
            options={'managed': False},
        ),
    ]
