# Generated by Django 2.1.15 on 2021-01-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvpsyndromic', '0003_auto_20210126_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='TStg1Cov2',
            fields=[
                ('operator', models.CharField(blank=True, db_column='Operator', max_length=255, null=True)),
                ('kitname', models.CharField(blank=True, db_column='KitName', max_length=255, null=True)),
                ('kitlot', models.CharField(blank=True, db_column='KitLot', max_length=255, null=True)),
                ('kitexp', models.DateTimeField(blank=True, db_column='KitExp', null=True)),
                ('refcov2_date', models.DateTimeField(blank=True, db_column='RefCoV2_Date', null=True)),
                ('sample', models.CharField(blank=True, db_column='Sample', max_length=25, primary_key=True, serialize=False)),
                ('refcov2_well', models.CharField(blank=True, db_column='RefCoV2_Well', max_length=5, null=True)),
                ('refcov2_cqvalue', models.CharField(blank=True, db_column='RefCoV2_CqValue', max_length=25, null=True)),
                ('refcov2_interp', models.CharField(blank=True, db_column='RefCoV2_Interp', max_length=25, null=True)),
                ('refcov2notes', models.CharField(blank=True, db_column='RefCoV2Notes', max_length=255, null=True)),
                ('excl_flag', models.IntegerField(db_column='Excl_Flag')),
                ('userid', models.CharField(blank=True, max_length=255, null=True)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_stg1_COV2',
                'managed': False,
            },
        ),
    ]
