# Generated by Django 2.1.15 on 2021-02-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvpsyndromic', '0004_tstg1cov2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tstg1brpcr',
            name='cq',
        ),
        migrations.RemoveField(
            model_name='tstg1brpcr',
            name='interp',
        ),
        migrations.RemoveField(
            model_name='tstg1brpcrupdate',
            name='cq',
        ),
        migrations.RemoveField(
            model_name='tstg1brpcrupdate',
            name='interp',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='refcov2_cqvalue',
        ),
        migrations.AddField(
            model_name='tstg1brpcr',
            name='cov2_cq',
            field=models.CharField(blank=True, db_column='COV2_Cq', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcr',
            name='cov2_interp',
            field=models.CharField(blank=True, db_column='COV2_Interp', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcr',
            name='infa_cq',
            field=models.CharField(blank=True, db_column='InfA_Cq', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcr',
            name='infa_interp',
            field=models.CharField(blank=True, db_column='InfA_Interp', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcr',
            name='infb_cq',
            field=models.CharField(blank=True, db_column='InfB_Cq', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcr',
            name='infb_interp',
            field=models.CharField(blank=True, db_column='InfB_Interp', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcr',
            name='rp_cq',
            field=models.CharField(blank=True, db_column='RP_Cq', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcr',
            name='rp_interp',
            field=models.CharField(blank=True, db_column='RP_Interp', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcrupdate',
            name='cov2_cq',
            field=models.CharField(blank=True, db_column='COV2_Cq', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcrupdate',
            name='cov2_interp',
            field=models.CharField(blank=True, db_column='COV2_Interp', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcrupdate',
            name='infa_cq',
            field=models.CharField(blank=True, db_column='InfA_Cq', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcrupdate',
            name='infa_interp',
            field=models.CharField(blank=True, db_column='InfA_Interp', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcrupdate',
            name='infb_cq',
            field=models.CharField(blank=True, db_column='InfB_Cq', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcrupdate',
            name='infb_interp',
            field=models.CharField(blank=True, db_column='InfB_Interp', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcrupdate',
            name='rp_cq',
            field=models.CharField(blank=True, db_column='RP_Cq', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1brpcrupdate',
            name='rp_interp',
            field=models.CharField(blank=True, db_column='RP_Interp', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_n1_cpvalue',
            field=models.CharField(blank=True, db_column='RefCov2_N1_CpValue', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_n2_cpvalue',
            field=models.CharField(blank=True, db_column='RefCov2_N2_CpValue', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_rpp_cpvalue',
            field=models.CharField(blank=True, db_column='RefCov2_RPP_CpValue', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1ecrfupdate',
            name='subject_ethnicity',
            field=models.CharField(blank=True, db_column='Subject_Ethnicity', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tstg1ecrfupdate',
            name='subject_race',
            field=models.CharField(blank=True, db_column='Subject_Race', max_length=50, null=True),
        ),
    ]
