# Generated by Django 2.1.15 on 2021-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvpsyndromic', '0005_auto_20210201_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='kitexp',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='kitlot',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='kitname',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='refcov2_date',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='refcov2_interp',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='refcov2_n1_cpvalue',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='refcov2_n2_cpvalue',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='refcov2_rpp_cpvalue',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='refcov2_well',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='refcov2notes',
        ),
        migrations.RemoveField(
            model_name='tstg1cov2update',
            name='sample',
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_kit_expiration_date',
            field=models.DateTimeField(blank=True, db_column='RefCov2_Kit_Expiration_Date', null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_kit_lotid',
            field=models.CharField(blank=True, db_column='RefCov2_Kit_LotID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_kit_name',
            field=models.CharField(blank=True, db_column='RefCov2_Kit_Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_n1_concentration',
            field=models.CharField(blank=True, db_column='RefCov2_N1_Concentration', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_n1_droplet_count',
            field=models.CharField(blank=True, db_column='RefCov2_N1_Droplet_Count', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_n2_concentration',
            field=models.CharField(blank=True, db_column='RefCov2_N2_Concentration', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_n2_droplet_count',
            field=models.CharField(blank=True, db_column='RefCov2_N2_Droplet_Count', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_notes',
            field=models.TextField(blank=True, db_column='RefCov2_Notes', null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_operator',
            field=models.CharField(blank=True, db_column='RefCov2_Operator', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_result_interpretation',
            field=models.CharField(blank=True, db_column='RefCov2_Result_Interpretation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_rp_concentration',
            field=models.CharField(blank=True, db_column='RefCov2_RP_Concentration', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_rp_droplet_count',
            field=models.CharField(blank=True, db_column='RefCov2_RP_Droplet_Count', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_test_date',
            field=models.DateTimeField(blank=True, db_column='RefCov2_Test_Date', null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_test_name',
            field=models.CharField(blank=True, db_column='RefCov2_Test_Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='refcov2_well_id',
            field=models.CharField(blank=True, db_column='RefCov2_Well_ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tstg1cov2update',
            name='sampleid',
            field=models.CharField(blank=True, db_column='SampleID', max_length=25, null=True),
        ),
    ]
