"""
Django settings for repository project.

Generated by 'django-admin startproject' using Django 2.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/
For the full list of settings and their values, see
    'django_filters',
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c%mzvoq&17!72ejcui21v5ex8o8r*k1em!u#4l5^xf(c$k%0%4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =True 

ALLOWED_HOSTS = ['10.241.200.50','10.17.80.13','usredlxd01.global.bio-rad.com','uscdm.global.bio-rad.com','global.bio-rad.com' ]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'search.apps.SearchConfig',
    #'django_filters',
 #   'django_tables2',
    'dal',
    'dal_select2',  
#    'whoosh',
    'ihab',
    'cdm_home',
    'crispy_forms',
    'rest_framework',
    'django_static_jquery',
    'django_filters',
    'rvpsyndromic',
    'rdt',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django_plotly_dash.middleware.BaseMiddleware',
    #'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
]

ROOT_URLCONF = 'repository.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'repository.wsgi.application'


SESSION_EXPIRE_SECONDS = 900 
SESSION_EXPIRE_AFTER_LAST_ACTIVITY =True
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	'ENGINE':"sql_server.pyodbc",
	'USER':"DjangoConnect",
	'PASSWORD':"Data4You",
	'NAME':"Repository",
	'OPTIONS':{
			'dsn':'SQLServerDatabase',
			'driver':'SQL Server Native Client 11.0'
		},

    },
    'ihab': {
	'ENGINE':"sql_server.pyodbc",
	'USER':"DjangoConnect",
	'PASSWORD':"Data4You",
	#'NAME':"DK_Test_ClinTrial_IHD_ABID",
	'NAME':"IHAB",
	'OPTIONS':{
			'dsn':'SQLServerDatabase',
			'driver':'SQL Server Native Client 11.0'
		},

    },
    'rvpsyndromic': {
	'ENGINE':"sql_server.pyodbc",
	'USER':"DjangoConnect",
	'PASSWORD':"Data4You",
	#'NAME':"DK_Test_ClinTrial_IHD_ABID",
	'NAME':"RVP",
	'OPTIONS':{
			'dsn':'SQLServerDatabase',
			'driver':'SQL Server Native Client 11.0'
		},

    }
}

# Location of database routers
DATABASE_ROUTERS = ['db_routers.AppRouter']


HAYSTACK_CONNECTIONS ={
	'default':{
			'ENGINE':'haystack.backends.whoosh_backend.WhooshEngine',
			'PATH': os.path.join(BASE_DIR, 'whoosh/'),
	
	},
}
#
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATETIME_INPUT_FORMATS = ['%m/%d/%y',]

#CSRF security
#CSRF_COOKIE_SECURE= True
#SESSION_COOKIE_SECURE =True
#Cross Site Security
SECURE_BROWSER_XSS_FILTER=True
SECURE_CONTENT_TYPE_NOSNIFF=True
#http -> https 
#SECURE_SSL_REDIRECT=True
#Clickjacking
X_FRAME_OPTIONS='DENY'

#MESSAGE_STORAGE ='django.contrib.messages.storage.cookie.CookieStorage'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
#STATIC_DIRS =( os.path.join(BASE_DIR, 'static'))# for dev, comment out when pushing to production
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles/')# production, comment out when pushing to development

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGOUT_URL ='/'
LOGIN_REDIRECT ='/'

#EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'
EMAIL_HOST= "smtp.bio-rad.com"#"smtp-mail.outlook.com"
DEFAULT_FROM_EMAIL = "cdm_webmaster@bio-rad.com"#"webmastercdmbiorad@outlook.com"
#EMAIL_HOST_USER= "webmastercdmbiorad@outlook.com"
#EMAIL_HOST_PASSWORD= "Bi0R@d2020"
EMAIL_PORT= 25 #port 25 is outlook port #
EMAIL_USE_TLS= True
